version: "3.9"
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    networks:
      default:
        aliases:
          - cl-api.dev
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
