name: Build and Deploy SQL Ledger Demo - karoliina-neas-12769

on:
  push:
    branches:
      - main
    paths:
      - "sql-ledger-frontend/**"
  workflow_dispatch:

concurrency:
  group: main_branch_deploy
  cancel-in-progress: true

defaults:
  run:
    working-directory: sql-ledger-frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.ACR_REGISTRY }}/sql-ledger-demo:${{ github.sha }}
          docker push ${{ secrets.ACR_REGISTRY }}/sql-ledger-demo:${{ github.sha }}
