name: Issues and work tracking
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
jobs:
  todos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Issues for Todos in Python Code
        uses: ribtoks/tdg-github-action@master
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          REF: ${{ github.ref }}
          INCLUDE_PATTERN: "\\.(py)$"
